---
title: "Engagement States"
author: "Martin Monkman"
date: "September 2, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Employee Engagement

Employee engagement is made up of three components:
* job satisfaction
* organization satisfaction
* commitment 

This chart ...

```{r echo = FALSE, message = FALSE}

# preliminaries

setwd("C:/@data/GitHub/WES-engagement-states")

library(ggplot2)
library(dplyr)

eng_state_data <- read.csv("./data/eng_states_data.csv")

eng_state_data <- eng_state_data %>%
  group_by(ORGID) %>%
  mutate(org_pct = Employees/sum(Employees)*100)

head(eng_state_data)

# set the sort function 

eng_state_data$Engagement.State <- factor(eng_state_data$Engagement.State, 
       levels = c("Engaged", "Moderately Engaged",
                  "Happily Detached", "Unhappily Dedicated",
                  "Minimally Engaged", "Disengaged"))
         

eng_state_data <- eng_state_data %>%
  arrange(ORG, Engagement.State)

eng_state_data

```


### The Plot

Basic plots

```{r}

eng_state_plot <- ggplot(subset(eng_state_data, ORGID == "OWL",),
            aes(x = Commitment, y = Satisfaction))

eng_state_plot + 
  geom_point(aes(size = org_pct))

eng_state_plot + 
  geom_point(aes(size = org_pct), shape = 21, colour = "black", fill = "cornsilk") +
  scale_size_area(max_size = 65, guide=FALSE)

# set axis

eng_state_plot + 
  geom_point(aes(size = org_pct), shape = 21, colour = "black", fill = "cornsilk") +
  scale_size_area(max_size = 50, guide=FALSE) +
  xlim(0, 100) +
  ylim(0, 100)



```


Add colour to the balloons

1. Using a Colour Brewer palette -- light to dark

```{r}

eng_state_plot <- 
  ggplot(subset(eng_state_data, ORGID == "OWL",),
            aes(x = Commitment, y = Satisfaction, fill = Engagement.State)) + 
  geom_point(aes(size = org_pct, stat="identity"), 
             shape = 21, colour = "black") +
  scale_size_area(max_size = 50, guide=FALSE) + 
  xlim(0,100) + ylim(0,100) +
  scale_fill_manual(values=c("#edf8fb", "#ccece6", "#99d8c9", 
                               "#66c2a4", "#2ca25f", "#006d2c"))


eng_state_plot  


```



```{r}

eng_state_plot <- 
  ggplot(subset(eng_state_data, ORGID == "OWL",),
            aes(x = Commitment, y = Satisfaction, fill = Engagement.State)) + 
  geom_point(aes(size = org_pct, stat="identity"), 
             shape = 21, colour = "black") +
  scale_size_area(max_size = 50, guide=FALSE) + 
  xlim(0,120) + ylim(0,120) +
  scale_fill_manual(values=c("#00348a", "#0057e7", "#FFD37F", 
                               "#ffa700", "#E68179", "#d62d20"))


eng_state_plot  


```

Add:

* colour palette (to above plot)

* sort by rank (not alphabetical)

* numeric labels

* theme


-30-
